[[plugins]]
repo = 'Shougo/dein.vim'

# 閉じ括弧
[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_add = '''
source ~/.config/nvim/plugins/auto-pairs.vim
'''

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = false
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

# ファイラー
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
source ~/.config/nvim/plugins/fern.vim
'''

# fern plugins >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
depends = ['fern.vim']
on_cmd = ['Fern']

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
depends = ['fern.vim']

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
depends = ['fern.vim', 'nerdfont.vim']

# [[plugins]]
# repo = 'yuki-yano/fern-preview.vim'
# depends = ['fern.vim']

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
depends = ['fern.vim', 'fzf']

[[plugins]]
repo = 'lambdalisue/fern-ssh'
depends = ['fern.vim']
# fern plugins <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

# gruvboxのデザイン
[[plugins]]
repo = 'morhetz/gruvbox'
hook_add = '''
source ~/.config/nvim/plugins/gruvbox.vim
'''

# yankをハイライトする
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
source ~/.config/nvim/plugins/vim-highlightedyank.vim
'''

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

# ステータスバー
[[plugins]]
repo = 'vim-airline/vim-airline.git'
hook_add = '''
source ~/.config/nvim/plugins/vim-airline.vim
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes.git'

# gcでコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'

# saiw) => (test)
[[plugins]]
repo = 'machakann/vim-sandwich'

# input: i,
# output: 
# ...........
# a , b , cccccccc , d , e
# └─── a, ──┘
[[plugins]]
repo = 'wellle/targets.vim'


[[plugins]]
repo = 'junegunn/fzf'
build = '''
./install -all
'''
[[plugins]]
repo = 'junegunn/fzf.vim'


# 日本語help
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# 色付き括弧
[[plugins]]
repo = 'luochen1990/rainbow'
hook_add = '''
source ~/.config/nvim/plugins/rainbow.vim
'''
# ウィンドウのサイズ変更
# [[plugins]]
# repo = 'simeji/winresizer'
# hook_add = '''
# source = ~/.config/nvim/plugins/winresizer.vim
# '''

# nerdtreeにgitのステータスを表示
[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'

# markdown preview
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
sh -c "cd app && yarn install"
'''
hook_add = '''
source ~/.config/nvim/plugins/markdown-preview.vim
'''

# 置換をプレビュー
[[plugins]]
repo = 'markonm/traces.vim'

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
source ~/.config/nvim/plugins/iceberg.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/vim-quickrun.vim
'''

[[plugins]]
repo = 'preservim/vimux'

[[plugins]]
repo = 'sheerun/vim-polyglot'

# [[plugins]]
# repo = 'nathanaelkane/vim-indent-guides'
# hook_add = '''
# source ~/.config/nvim/plugins/vim-indent-guides.vim
# '''
[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_add = '''
source ~/.config/nvim/plugins/vim-easy-align.vim
'''

# [[plugins]]
# repo = 'christoomey/vim-tmux-navigator'

# pythonのerrorformat設定
[[plugins]]
repo = 'aliev/vim-compiler-python'

#quickfix
[[plugins]]
repo = 'yssl/QFEnter'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
hook_add = '''
source ~/.config/nvim/plugins/vim-asterisk.vim
'''

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'kevinhwang91/nvim-bqf'

[[plugins]]
repo = 'honza/vim-snippets'

# [[plugins]]
# repo = 'dense-analysis/ale'
# hook_source = '''
# let g:ale_disable_lsp = 1
# '''

# color
[[plugins]]
repo = 'flazz/vim-colorschemes'
# color
[[plugins]]
repo = 'sainnhe/everforest'
hook_add = '''
source ~/.config/nvim/plugins/everforest.vim
'''
# color
[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_add = '''
source ~/.config/nvim/plugins/ayu-vim.vim
'''

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
hook_add = '''
source ~/.config/nvim/plugins/asynctasks.vim
'''
[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_add = '''
source ~/.config/nvim/plugins/asyncrun.vim
'''


[[plugins]]
repo = 'vim-test/vim-test'

[[plugins]]
repo = 'tpope/vim-dispatch'

[[plugins]]
repo = 'mg979/vim-visual-multi'
hook_add = '''
source ~/.config/nvim/plugins/vim-visual-multi.vim
'''

[[plugins]]
repo = 'vim-skk/eskk.vim'
hook_add = '''
source ~/.config/nvim/plugins/eskk.vim
'''

[[plugins]]
repo = 'deton/jasegment.vim'

[[plugins]]
repo = 'tomasiser/vim-code-dark'


[[plugins]]
repo = 'dstein64/vim-startuptime'

[[plugins]]
repo = 'folke/noice.nvim'
on_event = 'VimEnter'
hook_add = '''
    source ~/.config/nvim/plugins/noice.lua
'''

[[plugins]]
repo = 'rcarriga/nvim-notify'
on_event = 'VimEnter'
hook_add = '''
    source ~/.config/nvim/plugins/nvim-notify.lua
'''

[[plugins]]
repo = 'MunifTanjim/nui.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'sindrets/diffview.nvim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
source ~/.config/nvim/plugins/emmet-vim.vim
'''

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
