[[plugins]]
repo = 'puremourning/vimspector'
build = '''
./install_gadget.py --all
'''
hook_post_source = '''
source ~/.config/nvim/plugins/vimspector.vim
'''
on_func = [
  'vimspector#Launch()',
  'vimspector#ToggleBreakpoint',
  'vimspector#Continue',
]

#{{{ fern
# ファイラー
[[plugins]]
repo = 'lambdalisue/fern.vim'
hook_add = '''
source ~/.config/nvim/plugins/fern.vim
'''
on_cmd = 'Fern'

#{{{fern plugins
[[plugins]]
repo = 'lambdalisue/fern-bookmark.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-git-status.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/nerdfont.vim'
on_source = 'fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-nerdfont.vim'
on_source = ['fern.vim', 'nerdfont.vim']

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
on_source = ['fern.vim', 'fzf']

[[plugins]]
repo = 'lambdalisue/fern-ssh'
on_source = 'fern.vim'
#}}}
#}}}

#{{{colorschemes
[[plugins]]
repo = 'flazz/vim-colorschemes'
on_event = ['ColorSchemePre']

# color
[[plugins]]
repo = 'sainnhe/everforest'
hook_post_source = '''
source ~/.config/nvim/plugins/everforest.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_post_source = '''
source ~/.config/nvim/plugins/ayu-vim.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'morhetz/gruvbox'
hook_post_source = '''
source ~/.config/nvim/plugins/gruvbox.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'tomasiser/vim-code-dark'
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_post_source = '''
source ~/.config/nvim/plugins/iceberg.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_post_source = """
let g:solarized_termcolors=256
"""
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'shaunsingh/nord.nvim'

#}}}

#{{{filetype
[[plugins]]
repo = 'lervag/vimtex'
hook_post_source = '''
source ~/.config/nvim/plugins/vimtex.vim
'''
on_ft = 'tex'

[[plugins]]
repo = 'previm/previm'
on_ft = ['mermaid']
hook_post_source = '''
source ~/.config/nvim/plugins/previm.vim
'''

# markdown preview
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = '''
sh -c "cd app && yarn install"
'''
hook_post_source = '''
source ~/.config/nvim/plugins/markdown-preview.vim
'''

[[plugins]]
repo = 'aliev/vim-compiler-python'
on_ft = ['python', 'py']

[[plugins]]
repo = 'yssl/QFEnter'
on_ft = ['qf']

[[plugins]]
repo = 'kevinhwang91/nvim-bqf'
on_ft = ['qf']

#}}}

#{{{ on_cmd

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_post_source = '''
source ~/.config/nvim/plugins/vim-quickrun.vim
'''
on_cmd = 'QuickRun'
depends = ['vimproc.vim']

[[plugins]]
repo = 'skywind3000/asynctasks.vim'
hook_add = '''
source ~/.config/nvim/plugins/asynctasks.vim
'''
depends = ['asyncrun.vim']
on_cmd = ['AsyncTask', 'AsyncTaskMacro', 'AsyncTaskList', 'AsyncTaskEdit']

[[plugins]]
repo = 'skywind3000/asyncrun.vim'
hook_add = '''
source ~/.config/nvim/plugins/asyncrun.vim
'''
on_cmd = ['AsyncRun', 'AsyncStop']

[[plugins]]
repo = 'preservim/vimux'
on_cmd = ['Vimux']

[[plugins]]
repo = 'sindrets/diffview.nvim'
depends = ['plenary.nvim']
on_cmd = ['DiffviewOpen']

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'
on_cmd = 'DeinUpdate'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_cmd = ['Git']

#}}}

#{{{BufReadPre

# 色付き括弧
[[plugins]]
repo = 'luochen1990/rainbow'
hook_post_source = '''
source ~/.config/nvim/plugins/rainbow.vim
'''
on_event = 'BufReadPre'

[[plugins]]
repo = 'sheerun/vim-polyglot'
on_event = 'BufReadPre'

# }}}

#{{{BufReadPost

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_post_source = '''
source ~/.config/nvim/plugins/vim-highlightedyank.vim
'''
on_event = 'BufReadPost'

# gcでコメントアウト
[[plugins]]
repo = 'tpope/vim-commentary'
on_event = 'BufReadPost'

[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'BufReadPost'

[[plugins]]
repo = 'wellle/targets.vim'
on_event = 'BufReadPost'

# 置換をプレビュー
[[plugins]]
repo = 'markonm/traces.vim'
on_event = 'BufReadPost'

[[plugins]]
repo = 'junegunn/vim-easy-align'
hook_post_source = '''
source ~/.config/nvim/plugins/vim-easy-align.vim
'''
on_event = 'BufReadPost'

[[plugins]]
repo = 'haya14busa/vim-asterisk'
hook_post_source = '''
source ~/.config/nvim/plugins/vim-asterisk.vim
'''
on_event = 'BufReadPost'

[[plugins]]
repo = 'mg979/vim-visual-multi'
hook_post_source = '''
source ~/.config/nvim/plugins/vim-visual-multi.vim
'''
on_event = 'BufReadPost'

[[plugins]]
repo = 'deton/jasegment.vim'
on_event = 'BufReadPost'

[[plugins]]
repo = 'tyru/open-browser.vim'
on_event = 'BufReadPost'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'BufReadPost'

# }}}

#{{{ InsertEnter
[[plugins]]
repo = 'vim-skk/eskk.vim'
hook_post_source = '''
source ~/.config/nvim/plugins/eskk.vim
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'jiangmiao/auto-pairs'
hook_post_source = '''
source ~/.config/nvim/plugins/auto-pairs.vim
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'honza/vim-snippets'
on_event = 'InsertEnter'

[[plugins]]
repo = 'mattn/emmet-vim'
hook_post_source = '''
source ~/.config/nvim/plugins/emmet-vim.vim
'''
on_event = 'InsertEnter'

# }}}

#{{{ VimEnter

[[plugins]]
repo = 'folke/noice.nvim'
hook_source = '''
    source ~/.config/nvim/lua/plugins/noice.lua
'''
depends = ['nui.nvim', 'nvim-notify']
on_event = 'VimEnter'

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_event = 'VimEnter'

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_event = 'VimEnter'

[[plugins]]
repo = 'vim-test/vim-test'
depends = ['vim-dispatch']
hook_add = '''
let g:test#strategy = 'dispatch'
'''
on_event = 'VimEnter'

# }}}

#{{{ timeout

#}}}

#{{{ depended

[[plugins]] # vim-quickrun
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]] # diffview.nvim
repo = 'nvim-lua/plenary.nvim'

[[plugins]] # noice.nvim
repo = 'rcarriga/nvim-notify'
hook_source = '''
source ~/.config/nvim/lua/plugins/nvim-notify.lua
'''

[[plugins]] # noice.nvim
repo = 'MunifTanjim/nui.nvim'

[[plugins]] # vim-test
repo = 'tpope/vim-dispatch'

#}}}
