[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = false
rev = 'release'
hook_add = '''
source ~/.config/nvim/plugins/coc.vim
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
source ~/.config/nvim/plugins/lightline.vim
'''

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
on_source = 'lightline.vim'
