[[plugins]]
repo = 'puremourning/vimspector'
build = '''
./install_gadget.py --all
'''
hook_post_source = '''
source ~/.config/nvim/plugins/vimspector.vim
'''
on_func = [
  'vimspector#Launch()',
  'vimspector#ToggleBreakpoint',
  'vimspector#Continue',
]

#{{{colorschemes
[[plugins]]
repo = 'flazz/vim-colorschemes'
on_event = ['ColorSchemePre']

# color
[[plugins]]
repo = 'sainnhe/everforest'
hook_post_source = '''
source ~/.config/nvim/plugins/everforest.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'ayu-theme/ayu-vim'
hook_post_source = '''
source ~/.config/nvim/plugins/ayu-vim.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'morhetz/gruvbox'
hook_post_source = '''
source ~/.config/nvim/plugins/gruvbox.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'tomasiser/vim-code-dark'
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_post_source = '''
source ~/.config/nvim/plugins/iceberg.vim
'''
on_event = ['ColorSchemePre']

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_post_source = """
let g:solarized_termcolors=256
"""
on_event = ['ColorSchemePre']
#}}}

[[plugins]]
repo = 'lervag/vimtex'
hook_post_source = '''
source ~/.config/nvim/plugins/vimtex.vim
'''
on_ft = 'tex'

[[plugins]]
repo = 'previm/previm'
on_ft = ['mermaid']
hook_post_source = '''
source ~/.config/nvim/plugins/previm.vim
'''
