vim.keymap.set('n', '<Space>', '<Nop>')
vim.keymap.set('n', ',', '<Nop>')

vim.keymap.set('n', '[q', ':<C-u>cprev<CR>', { silent = true, remap = false })
vim.keymap.set('n', ']q', ':<C-u>cnext<CR>', { silent = true, remap = false })
vim.keymap.set('n', '[b', ':bprevious<CR>', { silent = true })
vim.keymap.set('n', ']b', ':bnext<CR>', { silent = true })
vim.keymap.set('n', '[B', ':bfirst<CR>', { silent = true })
vim.keymap.set('n', ']B', ':blast<CR>', { silent = true })
vim.keymap.set('n', ']t', ':<C-u>tabnext<CR>', { silent = true })
vim.keymap.set('n', '[t', ':<C-u>tabprevious<CR>', { silent = true })
vim.keymap.set('n', '<Space>tc', ':<C-u>tabclose<CR>', { silent = true })

vim.keymap.set('n', 'H', '^')
vim.keymap.set('n', 'L', '$')
vim.keymap.set('n', ';', ':')
vim.keymap.set('n', ':', ';')

vim.keymap.set('n', 'k', 'gk')
vim.keymap.set('n', 'gk,', 'k')
vim.keymap.set('n', 'j', 'gj')
vim.keymap.set('n', 'gj,', 'j')


vim.keymap.set('n', '<Space>s', function()
  vim.cmd.source(vim.env.MYVIMRC)
end)
vim.keymap.set('n', '<Space>w', '<Cmd>write<CR>', { silent = true })
vim.keymap.set('n', '<Space>q', ':<C-u>quit<CR>', { silent = true })
vim.keymap.set('n', '<Space>Q', ':<C-u>quit!<CR>', { silent = true })
vim.keymap.set('n', '<Space>n', ':<C-u>nohls<CR>', { silent = true })
vim.keymap.set('n', '<Space>h', '<C-w>h')
vim.keymap.set('n', '<Space>j', '<C-w>j')
vim.keymap.set('n', '<Space>k', '<C-w>k')
vim.keymap.set('n', '<Space>l', '<C-w>l')
